<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Новое письмо</title>
</head>
<body style="width: 100%; color: #272727; margin: 0; padding: 0; line-height: 100%; font-family:arial, 'helvetica neue', helvetica, sans-serif;">
<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse;">
    <tr>
        <td>
            <table border="0" cellpadding="0" cellspacing="0" align="center" width="560"
                   style="border-collapse: collapse;">
                <tr>
                    <td align="center"
                        style="  border-collapse: collapse; text-align: center; border-bottom: #333333 1px solid; font-size: 18px;">
                        <p>${theme}</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table border="0" cellpadding="0" cellspacing="0" align="center" width="560"
                   style="border-bottom: #333333 1px solid; border-collapse: collapse;">
                <tr>
                    <td height="20" width="560"></td>
                </tr>
                <tr style="margin: 10px 10px 10px 10px;">
                    <td align="center"
                        style="border-collapse: collapse; font-size: 20px; text-align: center; color:#272727; background-color: #efefef; margin: 10px 10px 10px 10px;">
                        <p>${theme}</p>
                    </td>
                </tr>
                <tr>
                    <td width="560" align="left"
                        style=" min-height: 150px; border-collapse: collapse; margin: 20px 10px 20px 10px; font-size: 16px;">
                        <p style="line-height: 1.5;">${text}</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td>
            <table border="0" cellpadding="0" cellspacing="0" align="center" width="600"
                   style="background-color: #c4c4c4; padding: 10px 30px 10px 30px;">
                <tr>
                    <td align="left" style="margin: 0 0 0 0; border-collapse: collapse;">
                        <button style="color:#ffffff;background-color: #272727;border-radius: 20px; padding: 10px;">
                            <a style="color: #ffffff;" href="https://t.me/Bank_Prototype_Support_bot">
                                Задать свой тупой вопрос</a>
                        </button>
                    </td>
                    <td align="right" style="margin: 0 0 0 0; border-collapse: collapse;">
                        <p>©Группа компаний Oladushek IT, 2023</p>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>
</body>
</html>