server:
  address: 0.0.0.0
  port: ${PORT:8080}

jwt:
  lifetime: 30m
  secret: vahue

spring:
  mvc:
    cors:
      enabled: true
      allowed-origins: https://ldt-hack-track-5-frontend.vercel.app/
      allowed-methods: GET, POST, PUT, DELETE
      allowed-headers: "*"
      exposed-headers: Authorization
      allow-credentials: true
      max-age: 3600
  datasource:
    #url: jdbc:postgres://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}
    #url: jdbc:postgresql:/${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:railway}
    url: jdbc:postgresql://${PGHOST:monorail.proxy.rlwy.net}:${PGPORT:33044}/railway
    password: ${PGPASSWORD:A3Gb4Ad6f6C6654-d1EFFC5D*2EfaB*A}
    username: ${PGUSER:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: smtp.yandex.ru
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    username: JustForJunior@yandex.ru
    password: lxuchfpanzsoyius
    protocol: smtp