jwt:
  lifetime: 30m
  secret: vahue

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: 1234
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: smtp.yandex.ru
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
    username: JustForJunior@yandex.ru
    password: lxuchfpanzsoyius
    protocol: smtp